import { Artisan, Category, Product, Region, Review } from "@/types";

export const CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "Terracotta Pottery",
    slug: "terracotta-pottery",
    description: "Hand-thrown earthen vessels, indigenous urns, and sculptural clay crafts.",
    imageUrl: "https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?auto=format&fit=crop&w=800&q=80",
    itemCount: 42,
  },
  {
    id: "cat-2",
    name: "Block Print",
    slug: "block-print",
    description: "Authentic Ajrakh mud-resist, Sanganeri florals, and hand-loomed textiles.",
    imageUrl: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80",
    itemCount: 58,
  },
  {
    id: "cat-3",
    name: "Dhokra Metal",
    slug: "dhokra-metal",
    description: "Ancient lost-wax bell metal casting and handcrafted tribal bronze.",
    imageUrl: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80",
    itemCount: 29,
  },
  {
    id: "cat-4",
    name: "Blue Pottery",
    slug: "blue-pottery",
    description: "Powdered quartz stone, Egyptian paste, and cobalt Persian floral glazes.",
    imageUrl: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80",
    itemCount: 35,
  },
  {
    id: "cat-5",
    name: "Wood Carving",
    slug: "wood-carving",
    description: "Hand-chiseled walnut root jali work, Channapatna turnery, and teak carvings.",
    imageUrl: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80",
    itemCount: 24,
  },
];

export const REGIONS: Region[] = [
  {
    id: "reg-gujarat",
    name: "Gujarat",
    slug: "gujarat",
    state: "Gujarat",
    description: "Famed for Kutch terracotta, Ajrakh mud-resist block printing, and Rogan art.",
    imageUrl: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80",
    craftTraditions: ["Terracotta Pottery", "Ajrakh Block Print", "Rogan Art"],
  },
  {
    id: "reg-bengal",
    name: "Bengal",
    slug: "bengal",
    state: "Bengal",
    description: "Centuries-old lost-wax Dhokra bell metal casting, terracotta temples, and Kantha weaves.",
    imageUrl: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80",
    craftTraditions: ["Dhokra Lost-Wax Metal", "Terracotta Pottery", "Kantha Stitch"],
  },
  {
    id: "reg-rajasthan",
    name: "Rajasthan",
    slug: "rajasthan",
    state: "Rajasthan",
    description: "Home of Jaipur cobalt quartz blue pottery, miniature murals, and Dabu resist.",
    imageUrl: "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80",
    craftTraditions: ["Jaipur Blue Pottery", "Sanganeri Print", "Kundan Meenakari"],
  },
  {
    id: "reg-kashmir",
    name: "Kashmir",
    slug: "kashmir",
    state: "Kashmir",
    description: "Intricate walnut wood root lattice openwork, hand-spun Pashmina, and papier-mâché.",
    imageUrl: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=800&q=80",
    craftTraditions: ["Walnut Wood Carving", "Pashmina Weaving", "Sozni Embroidery"],
  },
  {
    id: "reg-bihar",
    name: "Bihar",
    slug: "bihar",
    state: "Bihar",
    description: "Sacred Mithila Madhubani line art, Sikki golden grass crafts, and stone relief.",
    imageUrl: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80",
    craftTraditions: ["Madhubani Painting", "Sikki Grass Craft"],
  },
  {
    id: "reg-karnataka",
    name: "Karnataka",
    slug: "karnataka",
    state: "Karnataka",
    description: "Channapatna natural lacquerware wood turning and Mysuru sandalwood carvings.",
    imageUrl: "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80",
    craftTraditions: ["Channapatna Lacquer Wood", "Bidriware Metal"],
  },
];

export const ARTISANS: Artisan[] = [
  {
    id: "art-devendra",
    shopName: "Prajapati Terracotta Guild",
    slug: "devendra-prajapati",
    artisanName: "Devendra Prajapati",
    bio: "Custodial master of indigenous Gujarat terracotta pottery, reviving abstract sculptural forms with tribal slip motifs.",
    story: "Trained by five generations of village potters in Kutch, Devendra uses alluvial clay from seasonal monsoon lakebeds, hand-turned and pit-fired with dried desert brush.",
    craftTradition: "Terracotta Pottery",
    state: "Gujarat",
    locality: "Bhuj, Kutch",
    isVerified: true,
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80",
    yearsOfExperience: 28,
    featuredQuote: "The clay listens before it turns. In simplicity lies eternity.",
    productCount: 8,
  },
  {
    id: "art-ismail",
    shopName: "Khatri Ajrakh Heritage",
    slug: "ismail-khatri",
    artisanName: "Ismail Khatri",
    bio: "Pioneering master of natural indigo and madder root block printing with hand-carved teak stamps.",
    story: "The Khatri lineage has practiced the 16-stage river washing and resist printing tradition in Dhamadka since the 17th century. Every design honors geometry, stars, and night skies.",
    craftTradition: "Ajrakh Block Print",
    state: "Gujarat",
    locality: "Ajrakhpur, Kutch",
    isVerified: true,
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80",
    yearsOfExperience: 34,
    featuredQuote: "When the wooden block kisses the cloth with indigo, history repeats itself in symmetry.",
    productCount: 12,
  },
  {
    id: "art-subhash",
    shopName: "Bikna Dokra Studio",
    slug: "subhash-karmakar",
    artisanName: "Subhash Karmakar",
    bio: "National master of non-ferrous lost-wax beeswax hollow metal casting in rural Bankura.",
    story: "Subhash coils fine beeswax threads around sculptured clay cores. Molten bronze melts the wax away in wood charcoal pits, creating unrepeatable ritual lamps and artifacts.",
    craftTradition: "Dhokra Lost-Wax Metal",
    state: "Bengal",
    locality: "Bikna, Bankura",
    isVerified: true,
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80",
    yearsOfExperience: 31,
    featuredQuote: "Fire gives permanent life to what the bee created with wax.",
    productCount: 9,
  },
  {
    id: "art-leela",
    shopName: "Leela Devi Blue Pottery",
    slug: "leela-devi",
    artisanName: "Leela Devi",
    bio: "State awardee master potter creating clayless quartz pottery painted with classical Persian botanical glazes.",
    story: "Working in Sanganer, Leela Devi mixes ground quartz stone, cullet glass, and natural gums, painting each piece with fine squirrel hair brushes and mineral glazes.",
    craftTradition: "Jaipur Blue Pottery",
    state: "Rajasthan",
    locality: "Sanganer, Jaipur",
    isVerified: true,
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80",
    yearsOfExperience: 26,
    featuredQuote: "No clay wheel touches our vessels; stone and indigo remember the desert light.",
    productCount: 14,
  },
  {
    id: "art-ghulam",
    shopName: "Jhelum Woodcraft Guild",
    slug: "ghulam-rasool",
    artisanName: "Ghulam Rasool",
    bio: "Master carver specializing in deep openwork (Jali) from seasoned Kashmiri walnut tree roots.",
    story: "Ghulam carves seasoned walnut wood that has been air-dried for years in Srinagar's cool climate. His deep lattice openwork takes weeks of precise hand chisel manipulation.",
    craftTradition: "Walnut Wood Carving",
    state: "Kashmir",
    locality: "Downtown Srinagar",
    isVerified: true,
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=300&q=80",
    yearsOfExperience: 38,
    featuredQuote: "The grain of the walnut tree guides the chisel; the craftsman merely reveals its spirit.",
    productCount: 11,
  },
];

export const PRODUCTS: Product[] = [
  // 1. Ceramic Vase (from screenshot)
  {
    id: "prod-vase",
    title: "Modern Ethnic Ceramic Vase – Terracotta Vase with Indigenous Pattern",
    slug: "modern-ethnic-ceramic-vase-terracotta-indigenous-pattern",
    description: "Elevate your home decor with this exquisite set of 2 modern ceramic vases, featuring a sculptural, abstract design that brings organic warmth to any contemporary space.",
    excerpt: "Elevate your home decor with this exquisite set of 2 modern ceramic vases, featuring a sculptural, abstract design that brings organic warmth to any contemporary space.",
    story: "Rooted in the indigenous terracotta craft of rural Gujarat, each vase is hand-thrown on manual stone wheels by Devendra Prajapati. Subtle tribal slip motifs are hand-carved before low-temperature reduction firing.",
    craftType: "Terracotta Pottery",
    categorySlug: "terracotta-pottery",
    categoryName: "Terracotta Pottery",
    regionSlug: "gujarat",
    regionName: "Gujarat",
    state: "Gujarat",
    provenanceTag: "Gujarat",
    byline: "By Devendra Prajapati",
    dimensions: "14\" H × 8\" Diameter",
    materials: "Natural riverbed terracotta clay, organic slip glaze, natural beeswax finish",
    careInstructions: "Wipe with a soft dry or slightly damp cloth. Avoid submerging in water.",
    priceDollars: 126.99,
    priceDisplay: "$126.99",
    originalPriceDisplay: "$155.00",
    badgeText: "Direct Artisan Pricing",
    subtitle: "Minimalist Abstract Matte Decor for Living Room, Shelf & Tabletop Styling",
    colorSwatches: [
      { name: "Raw Terracotta", hex: "#8A4B38" },
      { name: "Sand Matte", hex: "#C8BEAF" },
    ],
    bullets: [
      "Authentic raw smoked terracotta with burnished finish",
      "Hand-painted indigenous geometric motifs using iron-oxide minerals",
      "Wheel-thrown and low-fired in traditional wood-burning village kilns",
      "Treated with organic beeswax sealant on the interior",
    ],
    pricePaise: 1045000,
    originalPricePaise: 1250000,
    stock: 6,
    isMadeToOrder: false,
    leadTimeDays: 3,
    status: "PUBLISHED",
    artisan: ARTISANS[0],
    images: [
      {
        id: "img-vase-1",
        url: "https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?auto=format&fit=crop&w=1200&q=85",
        altText: "Modern Ethnic Ceramic Vase – Terracotta Vase with Indigenous Pattern on marble pedestal",
        isPrimary: true,
      },
      {
        id: "img-vase-2",
        url: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=1000&q=85",
        altText: "Artisanal handcrafted ceramic plates and dishes on wooden workshop table",
      },
      {
        id: "img-vase-3",
        url: "https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?auto=format&fit=crop&w=1000&q=85",
        altText: "Minimal white ceramic single flower vase on clean white reflective surface",
      },
    ],
    rating: 4.9,
    reviewCount: 38,
    tags: ["Terracotta", "Pottery", "Vase", "Gujarat", "Minimalist"],
    createdAt: "2026-09-01T10:00:00Z",
  },
  // 2. Ajrakh Throw (from screenshot)
  {
    id: "prod-throw",
    title: "Heritage Ajrakh Indigo Hand-Block Draped Throw",
    slug: "heritage-ajrakh-indigo-hand-block-draped-throw",
    description: "A poetic celebration of cosmic geometry, hand block-printed using hand-carved teak wood blocks. Each piece passes through 16 stages of natural indigo and harda river washing.",
    excerpt: "A poetic celebration of cosmic geometry, hand block-printed using hand-carved teak wood blocks. Each piece passes through 16 stages of natural indigo and harda river washing.",
    story: "Ismail Khatri's family in Dhamadka has maintained the secret mineral and vegetal dye recipes of Ajrakh since 1600. The intricate star and grid arrangements symbolize night skies in the desert.",
    craftType: "Block Print",
    categorySlug: "block-print",
    categoryName: "Block Print",
    regionSlug: "gujarat",
    regionName: "Gujarat",
    state: "Gujarat",
    provenanceTag: "Gujarat",
    byline: "By Ismail Khatri",
    dimensions: "90\" L × 60\" W",
    materials: "100% Handspun organic cotton, naturally fermented indigo, madder root, harda",
    careInstructions: "Gentle cold hand wash with mild pH-neutral detergent or dry clean.",
    priceDollars: 184.00,
    priceDisplay: "$184.00",
    pricePaise: 1520000,
    originalPricePaise: 1750000,
    stock: 4,
    isMadeToOrder: false,
    leadTimeDays: 5,
    status: "PUBLISHED",
    artisan: ARTISANS[1],
    images: [
      {
        id: "img-throw-1",
        url: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1000&q=85",
        altText: "Heritage Ajrakh Indigo Hand-Block Draped Throw with intricate artisan craft details",
        isPrimary: true,
      },
    ],
    rating: 5.0,
    reviewCount: 42,
    tags: ["Block Print", "Ajrakh", "Indigo", "Gujarat", "Textile"],
    createdAt: "2026-09-03T11:30:00Z",
  },
  // 3. Dhokra Lamp (from screenshot)
  {
    id: "prod-lamp",
    title: "Dhokra Lost-Wax Cast Brass Tribal Forest Lamp",
    slug: "dhokra-lost-wax-cast-brass-tribal-forest-lamp",
    description: "Crafted without a single seam using pure beeswax threads coiled around clay armatures, this heirloom sculpture houses soft candlelight through filigree openings.",
    excerpt: "Crafted without a single seam using pure beeswax threads coiled around clay armatures, this heirloom sculpture houses soft candlelight through filigree openings.",
    story: "Subhash Karmakar uses the prehistoric 4,000-year-old lost-wax hollow casting technique of Bankura. Every strand of bronze was once a rolled thread of wild bee wax, ensuring no two pieces can ever be duplicated.",
    craftType: "Dhokra Metal",
    categorySlug: "dhokra-metal",
    categoryName: "Dhokra Metal",
    regionSlug: "bengal",
    regionName: "Bengal",
    state: "Bengal",
    provenanceTag: "Bengal",
    byline: "By Subhash Karmakar",
    dimensions: "12\" H × 8\" W × 6\" D",
    materials: "Recycled brass, bronze, pure beeswax, alluvial clay core",
    careInstructions: "Dust with a dry brush. Apply brass wax once a year to retain warm golden patina.",
    priceDollars: 210.00,
    priceDisplay: "$210.00",
    pricePaise: 1735000,
    originalPricePaise: 1950000,
    stock: 3,
    isMadeToOrder: true,
    leadTimeDays: 10,
    status: "PUBLISHED",
    artisan: ARTISANS[2],
    images: [
      {
        id: "img-lamp-1",
        url: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1000&q=85",
        altText: "Dhokra Lost-Wax Cast Brass Tribal Forest Lamp artifact",
        isPrimary: true,
      },
    ],
    rating: 4.9,
    reviewCount: 29,
    tags: ["Dhokra", "Bronze", "Lamp", "Bengal", "Tribal"],
    createdAt: "2026-09-05T09:00:00Z",
  },
  // 4. Blue Pottery Vessel (from screenshot)
  {
    id: "prod-bluepottery-vessel",
    title: "Jaipur Persian Quartz Blue Pottery Vessel",
    slug: "jaipur-persian-quartz-blue-pottery-vessel",
    description: "Unlike traditional ceramics, Jaipur Blue Pottery uses no clay; instead, powdered quartz stone, glass, and natural gums form a durable ceramic that never loses its luster.",
    excerpt: "Unlike traditional ceramics, Jaipur Blue Pottery uses no clay; instead, powdered quartz stone, glass, and natural gums for durable ceramics that endure for centuries.",
    story: "Hand-painted with classical floral arrangements and rich cobalt tones by Leela Devi in Sanganer. The mineral luster reflects Persian influences imported during the Mughal courts.",
    craftType: "Blue Pottery",
    categorySlug: "blue-pottery",
    categoryName: "Blue Pottery",
    regionSlug: "rajasthan",
    regionName: "Rajasthan",
    state: "Rajasthan",
    provenanceTag: "Rajasthan",
    byline: "By Leela Devi",
    dimensions: "11\" H × 6\" Diameter",
    materials: "Ground quartz, glass, Fuller's earth, copper & cobalt oxides, natural glaze",
    careInstructions: "Wipe clean with a soft microfiber cloth. Decorative indoor vessel.",
    priceDollars: 94.50,
    priceDisplay: "$94.50",
    pricePaise: 780000,
    originalPricePaise: 920000,
    stock: 7,
    isMadeToOrder: false,
    leadTimeDays: 3,
    status: "PUBLISHED",
    artisan: ARTISANS[3],
    images: [
      {
        id: "img-bluepottery-1",
        url: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1000&q=85",
        altText: "Jaipur Persian Quartz Blue Pottery Vessel with classical Dutch floral still life painting",
        isPrimary: true,
      },
    ],
    rating: 4.8,
    reviewCount: 31,
    tags: ["Blue Pottery", "Ceramic", "Rajasthan", "Vase"],
    createdAt: "2026-09-08T14:15:00Z",
  },
  // 5. Walnut Carved Box (from screenshot)
  {
    id: "prod-walnut-box",
    title: "Walnut Wood Intricate Lattice Carved Box",
    slug: "walnut-wood-intricate-lattice-carved-box",
    description: "Hand-chiseled from a single block of Kashmiri walnut root, featuring deep openwork (Jali) inspired by the Mughal palace courtyards of Srinagar.",
    excerpt: "Hand-chiseled from a single block of Kashmiri walnut root, featuring deep openwork (Jali) inspired by the Mughal palace courtyards of Srinagar.",
    story: "Crafted by Ghulam Rasool from sustainably harvested, seasoned Kashmiri walnut wood (Doon Kul). The openwork lattice (Pinjrakari) is painstakingly carved with miniature gouges without power tools.",
    craftType: "Wood Carving",
    categorySlug: "wood-carving",
    categoryName: "Wood Carving",
    regionSlug: "kashmir",
    regionName: "Kashmir",
    state: "Kashmir",
    provenanceTag: "Kashmir",
    byline: "By Ghulam Rasool",
    dimensions: "9\" L × 6\" W × 4\" H",
    materials: "Seasoned walnut root wood, natural wax polish",
    careInstructions: "Keep away from excessive heat or direct moisture. Buff with natural wax occasionally.",
    priceDollars: 145.00,
    priceDisplay: "$145.00",
    pricePaise: 1195000,
    originalPricePaise: 1350000,
    stock: 5,
    isMadeToOrder: false,
    leadTimeDays: 4,
    status: "PUBLISHED",
    artisan: ARTISANS[4],
    images: [
      {
        id: "img-walnut-1",
        url: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1000&q=85",
        altText: "Walnut Wood Intricate Lattice Carved Box beside modern minimal plant and clock",
        isPrimary: true,
      },
    ],
    rating: 4.9,
    reviewCount: 22,
    tags: ["Wood Carving", "Walnut", "Kashmir", "Box", "Heirloom"],
    createdAt: "2026-09-10T16:00:00Z",
  },
];

export const REVIEWS: Review[] = [
  {
    id: "rev-1",
    productId: "prod-vase",
    authorName: "Ananya Deshmukh",
    rating: 5,
    title: "Sculptural perfection and authentic craft warmth",
    comment: "The vase looks even more stunning in person than in the photos. The subtle texture of natural terracotta brings tranquility to the room. Devendra Prajapati-ji's touch is evident.",
    verifiedPurchase: true,
    date: "2026-09-12",
    locality: "Bengaluru, Karnataka",
  },
  {
    id: "rev-2",
    productId: "prod-throw",
    authorName: "Rohan Singhal",
    rating: 5,
    title: "True heritage piece with authentic indigo smell",
    comment: "Knowing that this was block printed with 16 stages of river washing makes it a wonderful conversation starter. Ismail Khatri's family is legendary.",
    verifiedPurchase: true,
    date: "2026-09-18",
    locality: "New Delhi",
  },
  {
    id: "rev-3",
    productId: "prod-lamp",
    authorName: "Meera Subramanian",
    rating: 5,
    title: "An absolute treasure of Indian lost-wax casting",
    comment: "To have a genuine Dhokra piece from Bikna is a privilege. The beeswax filigree texture is breathtaking.",
    verifiedPurchase: true,
    date: "2026-09-22",
    locality: "Chennai, Tamil Nadu",
  },
];
