import { Artisan, Category, Product, Region, Review } from "@/types";

export const CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "Terracotta Pottery",
    slug: "terracotta-pottery",
    description: "Hand-thrown earthen vessels, indigenous urns, and sculptural clay crafts.",
    imageUrl: "https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?auto=format&fit=crop&w=800&q=80",
    itemCount: 42,
  },
  {
    id: "cat-2",
    name: "Block Print",
    slug: "block-print",
    description: "Authentic Ajrakh mud-resist, Sanganeri florals, and hand-loomed textiles.",
    imageUrl: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80",
    itemCount: 58,
  },
  {
    id: "cat-3",
    name: "Dhokra Metal",
    slug: "dhokra-metal",
    description: "Ancient lost-wax bell metal casting and handcrafted tribal bronze.",
    imageUrl: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80",
    itemCount: 29,
  },
  {
    id: "cat-4",
    name: "Blue Pottery",
    slug: "blue-pottery",
    description: "Powdered quartz stone, Egyptian paste, and cobalt Persian floral glazes.",
    imageUrl: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80",
    itemCount: 35,
  },
  {
    id: "cat-5",
    name: "Wood Carving",
    slug: "wood-carving",
    description: "Hand-chiseled walnut root jali work, Channapatna turnery, and teak carvings.",
    imageUrl: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80",
    itemCount: 24,
  },
];

export const REGIONS: Region[] = [
  {
    id: "reg-gujarat",
    name: "Gujarat",
    slug: "gujarat",
    state: "Gujarat",
    description: "Famed for Kutch terracotta, Ajrakh mud-resist block printing, and Rogan art.",
    imageUrl: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80",
    craftTraditions: ["Terracotta Pottery", "Ajrakh Block Print", "Rogan Art"],
  },
  {
    id: "reg-bengal",
    name: "Bengal",
    slug: "bengal",
    state: "Bengal",
    description: "Centuries-old lost-wax Dhokra bell metal casting, terracotta temples, and Kantha weaves.",
    imageUrl: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80",
    craftTraditions: ["Dhokra Lost-Wax Metal", "Terracotta Pottery", "Kantha Stitch"],
  },
  {
    id: "reg-rajasthan",
    name: "Rajasthan",
    slug: "rajasthan",
    state: "Rajasthan",
    description: "Home of Jaipur cobalt quartz blue pottery, miniature murals, and Dabu resist.",
    imageUrl: "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80",
    craftTraditions: ["Jaipur Blue Pottery", "Sanganeri Print", "Kundan Meenakari"],
  },
  {
    id: "reg-kashmir",
    name: "Kashmir",
    slug: "kashmir",
    state: "Kashmir",
    description: "Intricate walnut wood root lattice openwork, hand-spun Pashmina, and papier-mâché.",
    imageUrl: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=800&q=80",
    craftTraditions: ["Walnut Wood Carving", "Pashmina Weaving", "Sozni Embroidery"],
  },
  {
    id: "reg-bihar",
    name: "Bihar",
    slug: "bihar",
    state: "Bihar",
    description: "Sacred Mithila Madhubani line art, Sikki golden grass crafts, and stone relief.",
    imageUrl: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80",
    craftTraditions: ["Madhubani Painting", "Sikki Grass Craft"],
  },
  {
    id: "reg-karnataka",
    name: "Karnataka",
    slug: "karnataka",
    state: "Karnataka",
    description: "Channapatna natural lacquerware wood turning and Mysuru sandalwood carvings.",
    imageUrl: "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80",
    craftTraditions: ["Channapatna Lacquer Wood", "Bidriware Metal"],
  },
];

export const ARTISANS: Artisan[] = [
  {
    id: "art-devendra",
    shopName: "Prajapati Terracotta Guild",
    slug: "devendra-prajapati",
    artisanName: "Devendra Prajapati",
    bio: "Custodial master of indigenous Gujarat terracotta pottery, reviving abstract sculptural forms with tribal slip motifs.",
    story: "Trained by five generations of village potters in Kutch, Devendra uses alluvial clay from seasonal monsoon lakebeds, hand-turned and pit-fired with dried desert brush.",
    craftTradition: "Terracotta Pottery",
    state: "Gujarat",
    locality: "Bhuj, Kutch",
    isVerified: true,
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80",
    yearsOfExperience: 28,
    featuredQuote: "The clay listens before it turns. In simplicity lies eternity.",
    productCount: 8,
  },
  {
    id: "art-ismail",
    shopName: "Khatri Ajrakh Heritage",
    slug: "ismail-khatri",
    artisanName: "Ismail Khatri",
    bio: "Pioneering master of natural indigo and madder root block printing with hand-carved teak stamps.",
    story: "The Khatri lineage has practiced the 16-stage river washing and resist printing tradition in Dhamadka since the 17th century. Every design honors geometry, stars, and night skies.",
    craftTradition: "Ajrakh Block Print",
    state: "Gujarat",
    locality: "Ajrakhpur, Kutch",
    isVerified: true,
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80",
    yearsOfExperience: 34,
    featuredQuote: "When the wooden block kisses the cloth with indigo, history repeats itself in symmetry.",
    productCount: 12,
  },
  {
    id: "art-subhash",
    shopName: "Bikna Dokra Studio",
    slug: "subhash-karmakar",
    artisanName: "Subhash Karmakar",
    bio: "National master of non-ferrous lost-wax beeswax hollow metal casting in rural Bankura.",
    story: "Subhash coils fine beeswax threads around sculptured clay cores. Molten bronze melts the wax away in wood charcoal pits, creating unrepeatable ritual lamps and artifacts.",
    craftTradition: "Dhokra Lost-Wax Metal",
    state: "Bengal",
    locality: "Bikna, Bankura",
    isVerified: true,
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80",
    yearsOfExperience: 31,
    featuredQuote: "Fire gives permanent life to what the bee created with wax.",
    productCount: 9,
  },
  {
    id: "art-leela",
    shopName: "Leela Devi Blue Pottery",
    slug: "leela-devi",
    artisanName: "Leela Devi",
    bio: "State awardee master potter creating clayless quartz pottery painted with classical Persian botanical glazes.",
    story: "Working in Sanganer, Leela Devi mixes ground quartz stone, cullet glass, and natural gums, painting each piece with fine squirrel hair brushes and mineral glazes.",
    craftTradition: "Jaipur Blue Pottery",
    state: "Rajasthan",
    locality: "Sanganer, Jaipur",
    isVerified: true,
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80",
    yearsOfExperience: 26,
    featuredQuote: "No clay wheel touches our vessels; stone and indigo remember the desert light.",
    productCount: 14,
  },
  {
    id: "art-ghulam",
    shopName: "Jhelum Woodcraft Guild",
    slug: "ghulam-rasool",
    artisanName: "Ghulam Rasool",
    bio: "Master carver specializing in deep openwork (Jali) from seasoned Kashmiri walnut tree roots.",
    story: "Ghulam carves seasoned walnut wood that has been air-dried for years in Srinagar's cool climate. His deep lattice openwork takes weeks of precise hand chisel manipulation.",
    craftTradition: "Walnut Wood Carving",
    state: "Kashmir",
    locality: "Downtown Srinagar",
    isVerified: true,
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=300&q=80",
    yearsOfExperience: 38,
    featuredQuote: "The grain of the walnut tree guides the chisel; the craftsman merely reveals its spirit.",
    productCount: 11,
  },
  {
    id: "art-shankar",
    shopName: "Jangid Heritage Woodcarvers",
    slug: "shankar-lal-jangid",
    artisanName: "Shankar Lal Jangid",
    bio: "Master artisan of high-relief Sheesham and teak woodwork and traditional metal sculpting.",
    story: "Carrying forward a three-generation legacy in Churu and Jaipur, Shankar Lal sculpts architectural wood panels and heirloom timepieces using ancestral hand gouges.",
    craftTradition: "Wood Carving",
    state: "Rajasthan",
    locality: "Jaipur, Rajasthan",
    isVerified: true,
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80",
    yearsOfExperience: 32,
    featuredQuote: "Wood breathes long after the tree has fallen.",
    productCount: 15,
  },
  {
    id: "art-kalyan",
    shopName: "Joshi Pichwai Atelier",
    slug: "kalyan-joshi",
    artisanName: "Kalyan Joshi",
    bio: "National Award-winning master of Pichwai and Phad devotional miniature temple scrolls.",
    story: "Born into the renowned Joshi chhipa lineage of Bhilwara, Kalyan prepares mineral colors from lapis, vermilion, and 24-karat pure beaten gold leaf ground by hand on stone slabs.",
    craftTradition: "Miniature Painting",
    state: "Rajasthan",
    locality: "Bhilwara, Rajasthan",
    isVerified: true,
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80",
    yearsOfExperience: 35,
    featuredQuote: "Every brushstroke is a silent prayer to the divine cosmos.",
    productCount: 18,
  },
  {
    id: "art-zarina",
    shopName: "Begum Zardozi Karigari",
    slug: "zarina-begum",
    artisanName: "Zarina Begum",
    bio: "Celebrated master embroiderer of royal Awadh metallic wire zari and zardozi filigree.",
    story: "Working in old Lucknow, Zarina commands the wooden adda frame, anchoring pure silver and gold bullion wires onto fine silk velvets using curved ari needles.",
    craftTradition: "Zardozi Embroidery",
    state: "Uttar Pradesh",
    locality: "Chowk, Lucknow",
    isVerified: true,
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80",
    yearsOfExperience: 29,
    featuredQuote: "Gold and velvet preserve the grandeur of royal courts.",
    productCount: 10,
  },
  {
    id: "art-meenakshi",
    shopName: "Rathore Blue Quartz Studio",
    slug: "meenakshi-rathore",
    artisanName: "Meenakshi Rathore",
    bio: "Heritage craftswoman blending Jaipur blue quartz pottery with Persian floral glazes.",
    story: "Meenakshi creates clay-free vitreous tableware from ground quartz, natural copper oxide, and gum, hand-painting botanical motifs with squirrel hair brushes.",
    craftTradition: "Blue Pottery",
    state: "Rajasthan",
    locality: "Sanganer, Jaipur",
    isVerified: true,
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80",
    yearsOfExperience: 24,
    featuredQuote: "The cobalt hues mirror Rajasthan's clear winter skies.",
    productCount: 16,
  },
  {
    id: "art-rameshwar",
    shopName: "Chitrakar Kalamkari Guild",
    slug: "rameshwar-chitrakar",
    artisanName: "Rameshwar Chitrakar",
    bio: "Eminent practitioner of Srikalahasti freehand pen Kalamkari and organic mordant drawing.",
    story: "Rameshwar uses bamboo kalam reed pens dipped in fermented jaggery and iron to draw narrative Tree of Life scrolls washed in holy temple waters.",
    craftTradition: "Kalamkari Painting",
    state: "Andhra Pradesh",
    locality: "Srikalahasti, Andhra Pradesh",
    isVerified: true,
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80",
    yearsOfExperience: 33,
    featuredQuote: "The bamboo pen flows where mythology and nature intertwine.",
    productCount: 12,
  },
  {
    id: "art-bhuribai",
    shopName: "Bhuri Bai Gond Studio",
    slug: "bhuri-bai",
    artisanName: "Bhuri Bai",
    bio: "Padma Shri master artist preserving indigenous tribal canvas narratives and dot-line iconography.",
    story: "Bhuri Bai translates forest folklore, ancestral deities, and animist connections into vibrant rhythmic dots and mineral pigment expressions.",
    craftTradition: "Gond Art",
    state: "Madhya Pradesh",
    locality: "Bhopal, Madhya Pradesh",
    isVerified: true,
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80",
    yearsOfExperience: 40,
    featuredQuote: "Every living tree has a spirit; our art is its song.",
    productCount: 14,
  },
];

export const PRODUCTS: Product[] = [
  // 1. Ceramic Vase (from screenshot)
  {
    id: "prod-vase",
    title: "Modern Ethnic Ceramic Vase – Terracotta Vase with Indigenous Pattern",
    shortTitle: "Modern Ethnic Ceramic Vase –...",
    slug: "modern-ethnic-ceramic-vase-terracotta-indigenous-pattern",
    description: "Elevate your home decor with this exquisite set of 2 modern ceramic vases, featuring a sculptural, abstract design that brings organic warmth to any contemporary space.",
    excerpt: "Elevate your home decor with this exquisite set of 2 modern ceramic vases, featuring a sculptural, abstract design that brings organic warmth to any contemporary space.",
    story: "Rooted in the indigenous terracotta craft of rural Gujarat, each vase is hand-thrown on manual stone wheels by Devendra Prajapati. Subtle tribal slip motifs are hand-carved before low-temperature reduction firing.",
    craftType: "Terracotta Pottery",
    categorySlug: "pottery",
    categoryName: "Pottery",
    regionSlug: "gujarat",
    regionName: "Gujarat",
    state: "Gujarat",
    provenanceTag: "Gujarat",
    byline: "Devendra Prajapati",
    dimensions: "14\" H × 8\" Diameter",
    materials: "Natural riverbed terracotta clay, organic slip glaze, natural beeswax finish",
    careInstructions: "Wipe with a soft dry or slightly damp cloth. Avoid submerging in water.",
    priceDollars: 127.00,
    priceDisplay: "$127",
    originalPriceDisplay: "$155.00",
    badgeText: "Direct Artisan Pricing",
    subtitle: "Minimalist Abstract Matte Decor for Living Room, Shelf & Tabletop Styling",
    colorSwatches: [
      { name: "Raw Terracotta", hex: "#8A4B38" },
      { name: "Sand Matte", hex: "#C8BEAF" },
    ],
    bullets: [
      "Authentic raw smoked terracotta with burnished finish",
      "Hand-painted indigenous geometric motifs using iron-oxide minerals",
      "Wheel-thrown and low-fired in traditional wood-burning village kilns",
      "Treated with organic beeswax sealant on the interior",
    ],
    pricePaise: 1054100,
    originalPricePaise: 1250000,
    stock: 6,
    isMadeToOrder: false,
    leadTimeDays: 3,
    status: "PUBLISHED",
    artisan: ARTISANS[0],
    initialFavorited: true,
    images: [
      {
        id: "img-vase-1",
        url: "https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?auto=format&fit=crop&w=1200&q=85",
        altText: "Modern Ethnic Ceramic Vase – Terracotta Vase with Indigenous Pattern",
        isPrimary: true,
      },
      {
        id: "img-vase-2",
        url: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=1000&q=85",
        altText: "Artisanal handcrafted ceramic plates and dishes on wooden workshop table",
      },
    ],
    rating: 4.9,
    reviewCount: 38,
    tags: ["Terracotta", "Pottery", "Vase", "Gujarat", "Minimalist"],
    createdAt: "2026-09-01T10:00:00Z",
  },

  // 2. Hand-Carved Floral High-Relief Clock (from screenshot)
  {
    id: "prod-clock",
    title: "Hand-Carved Floral High-Relief Sheesham Clock",
    shortTitle: "Hand-Carved Floral High-Relief...",
    slug: "hand-carved-floral-high-relief-sheesham-clock",
    description: "Intricately hand-sculpted from aged Sheesham timber, featuring deep vegetal floral relief in concentric geometric arrangements.",
    excerpt: "Intricately hand-sculpted from aged Sheesham timber, featuring deep vegetal floral relief in concentric geometric arrangements.",
    story: "Shankar Lal Jangid carves seasoned Rajasthan rosewood with traditional gouges, honoring centuries-old architectural palace relief craft.",
    craftType: "Wood Carving",
    categorySlug: "wood-carving",
    categoryName: "Wood Carving",
    regionSlug: "rajasthan",
    regionName: "Rajasthan",
    state: "Rajasthan",
    provenanceTag: "Rajasthan",
    byline: "Shankar Lal Jangid",
    dimensions: "16\" Diameter × 2.5\" D",
    materials: "Solid aged Sheesham timber, organic beeswax polish, silent brass clockwork",
    careInstructions: "Dust regularly with soft dry cotton cloth. Keep away from humid bathrooms.",
    priceDollars: 700.00,
    priceDisplay: "$700",
    pricePaise: 5810000,
    originalPricePaise: 6500000,
    stock: 2,
    isMadeToOrder: true,
    leadTimeDays: 14,
    status: "PUBLISHED",
    artisan: ARTISANS.find((a) => a.id === "art-shankar") || ARTISANS[0],
    initialFavorited: false,
    images: [
      {
        id: "img-clock-1",
        url: "https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?auto=format&fit=crop&w=1000&q=85",
        altText: "Hand-Carved Floral High-Relief Sheesham Clock on wall with potted plant",
        isPrimary: true,
      },
    ],
    rating: 5.0,
    reviewCount: 16,
    tags: ["Wood Carving", "Clock", "Sheesham", "Rajasthan", "Heirloom"],
    createdAt: "2026-09-02T10:00:00Z",
  },

  // 3. Sacred Srinathji Gold-Leaf Pichwai (from screenshot)
  {
    id: "prod-pichwai",
    title: "Sacred Srinathji Gold-Leaf Pichwai Miniature Painting",
    shortTitle: "Sacred Srinathji Gold-Leaf Pichwai...",
    slug: "sacred-srinathji-gold-leaf-pichwai-miniature",
    description: "Devotional temple scroll painting executed with natural crushed stone minerals and illuminated with pure 24-karat gold leaf.",
    excerpt: "Devotional temple scroll painting executed with natural crushed stone minerals and illuminated with pure 24-karat gold leaf.",
    story: "Master Kalyan Joshi follows the Vallabhacharya Haveli tradition, grinding lapis lazuli and malachite on stone slabs with natural gum binding.",
    craftType: "Miniature Painting",
    categorySlug: "miniature-painting",
    categoryName: "Miniature Painting",
    regionSlug: "rajasthan",
    regionName: "Rajasthan",
    state: "Rajasthan",
    provenanceTag: "Rajasthan",
    byline: "Kalyan Joshi",
    dimensions: "30\" H × 22\" W",
    materials: "Khadi handmade cotton canvas, crushed mineral pigments, pure 24k gold leaf",
    careInstructions: "Keep framed under archival UV-protective museum glass.",
    priceDollars: 1500.00,
    priceDisplay: "$1500",
    pricePaise: 12450000,
    originalPricePaise: 14000000,
    stock: 1,
    isMadeToOrder: true,
    leadTimeDays: 21,
    status: "PUBLISHED",
    artisan: ARTISANS.find((a) => a.id === "art-kalyan") || ARTISANS[0],
    initialFavorited: false,
    images: [
      {
        id: "img-pichwai-1",
        url: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1000&q=85",
        altText: "Sacred Srinathji Gold-Leaf Pichwai Miniature Painting with classical floral composition",
        isPrimary: true,
      },
    ],
    rating: 5.0,
    reviewCount: 19,
    tags: ["Miniature Painting", "Pichwai", "Gold Leaf", "Rajasthan", "Temple Art"],
    createdAt: "2026-09-03T10:00:00Z",
  },

  // 4. Dhokra Primitive Tribal Bell-Metal (from screenshot)
  {
    id: "prod-dhokra-bag",
    title: "Dhokra Primitive Tribal Bell-Metal Lost-Wax Vessel",
    shortTitle: "Dhokra Primitive Tribal Bell-Metal...",
    slug: "dhokra-primitive-tribal-bell-metal-vessel",
    description: "Prehistoric lost-wax hollow casting crafted with rolled natural beeswax threads around organic clay armature.",
    excerpt: "Prehistoric lost-wax hollow casting crafted with rolled natural beeswax threads around organic clay armature.",
    story: "Executed with non-ferrous bronze alloys melted in pit hearths, preserving 4,000-year-old Mohenjo-daro metalworking traditions.",
    craftType: "Metalwork",
    categorySlug: "metalwork",
    categoryName: "Metalwork",
    regionSlug: "west-bengal",
    regionName: "West Bengal",
    state: "West Bengal",
    provenanceTag: "West Bengal",
    byline: "Shankar Lal Jangid",
    dimensions: "12\" H × 8\" W × 6\" D",
    materials: "Recycled brass, bronze, pure beeswax, alluvial clay core",
    careInstructions: "Dust gently with dry brush. Apply thin layer of natural beeswax annually.",
    priceDollars: 190.00,
    priceDisplay: "$190",
    pricePaise: 1577000,
    originalPricePaise: 1800000,
    stock: 4,
    isMadeToOrder: false,
    leadTimeDays: 5,
    status: "PUBLISHED",
    artisan: ARTISANS.find((a) => a.id === "art-shankar") || ARTISANS[0],
    initialFavorited: false,
    images: [
      {
        id: "img-dhokra-1",
        url: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=1000&q=85",
        altText: "Dhokra Primitive Tribal Bell-Metal craft vessel hanging on wall",
        isPrimary: true,
      },
    ],
    rating: 4.8,
    reviewCount: 23,
    tags: ["Metalwork", "Dhokra", "Bell Metal", "West Bengal", "Tribal"],
    createdAt: "2026-09-04T10:00:00Z",
  },

  // 5. Zardozi Hand-Embroidered Velvet (from screenshot)
  {
    id: "prod-zardozi",
    title: "Zardozi Hand-Embroidered Velvet Adornment Jewelry Box",
    shortTitle: "Zardozi Hand-Embroidered Velvet...",
    slug: "zardozi-hand-embroidered-velvet-adornment",
    description: "Opulent metallic wire embroidery sewn over heavy silk velvet with coiled metallic bullion, seed pearls, and dabka wires.",
    excerpt: "Opulent metallic wire embroidery sewn over heavy silk velvet with coiled metallic bullion, seed pearls, and dabka wires.",
    story: "Zarina Begum channels Awadh royal court traditions using the wooden adda frame and ari hooked needles in the historic quarters of Lucknow.",
    craftType: "Zardozi Embroidery",
    categorySlug: "zardozi-embroidery",
    categoryName: "Zardozi Embroidery",
    regionSlug: "uttar-pradesh",
    regionName: "Uttar Pradesh",
    state: "Uttar Pradesh",
    provenanceTag: "Uttar Pradesh",
    byline: "Zarina Begum",
    dimensions: "10\" L × 7\" W × 3\" H",
    materials: "Pure silk velvet, silver and gold-plated copper bullion, cultured pearls",
    careInstructions: "Store in soft cotton pouch. Spot clean only with dry velvet cloth.",
    priceDollars: 540.00,
    priceDisplay: "$540",
    pricePaise: 4482000,
    originalPricePaise: 5200000,
    stock: 3,
    isMadeToOrder: false,
    leadTimeDays: 7,
    status: "PUBLISHED",
    artisan: ARTISANS.find((a) => a.id === "art-zarina") || ARTISANS[0],
    initialFavorited: false,
    images: [
      {
        id: "img-zardozi-1",
        url: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1000&q=85",
        altText: "Zardozi Hand-Embroidered Velvet gold jewelry and adornments",
        isPrimary: true,
      },
    ],
    rating: 4.9,
    reviewCount: 27,
    tags: ["Zardozi Embroidery", "Velvet", "Gold Wire", "Uttar Pradesh", "Royal"],
    createdAt: "2026-09-05T10:00:00Z",
  },

  // 6. Heritage Ajrakh 16-Stage Indigo (from screenshot)
  {
    id: "prod-ajrakh-throw",
    title: "Heritage Ajrakh 16-Stage Indigo Botanical Throw",
    shortTitle: "Heritage Ajrakh 16-Stage Indigo...",
    slug: "heritage-ajrakh-16-stage-indigo-botanical-throw",
    description: "A cosmic celebration of geometric order and river chemistry, printed in 16 laborious stages using carved teak blocks and natural indigo.",
    excerpt: "A cosmic celebration of geometric order and river chemistry, printed in 16 laborious stages using carved teak blocks and natural indigo.",
    story: "Ismail Mohammad Khatri maintains the ancient Dhamadka tradition of mud-resist (gaj), alum printing, and naturally fermented indigo river baths.",
    craftType: "Block Printing",
    categorySlug: "block-printing",
    categoryName: "Block Printing",
    regionSlug: "gujarat",
    regionName: "Gujarat",
    state: "Gujarat",
    provenanceTag: "Gujarat",
    byline: "Ismail Mohammad Khatri",
    dimensions: "90\" L × 60\" W",
    materials: "100% Handspun organic cotton, naturally fermented indigo, madder root",
    careInstructions: "Cold gentle wash with pH-neutral detergent or dry clean.",
    priceDollars: 184.00,
    priceDisplay: "$184",
    pricePaise: 1527200,
    originalPricePaise: 1750000,
    stock: 5,
    isMadeToOrder: false,
    leadTimeDays: 4,
    status: "PUBLISHED",
    artisan: ARTISANS.find((a) => a.id === "art-ismail") || ARTISANS[1],
    initialFavorited: false,
    images: [
      {
        id: "img-ajrakh-1",
        url: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1000&q=85",
        altText: "Heritage Ajrakh 16-Stage Indigo Botanical Throw textile details",
        isPrimary: true,
      },
    ],
    rating: 5.0,
    reviewCount: 42,
    tags: ["Block Printing", "Ajrakh", "Indigo", "Gujarat", "Textile"],
    createdAt: "2026-09-06T10:00:00Z",
  },

  // 7. Jaipur Persian Quartz Blue Glazed (from screenshot)
  {
    id: "prod-blue-plates",
    title: "Jaipur Persian Quartz Blue Glazed Ceramic Dinner Plates",
    shortTitle: "Jaipur Persian Quartz Blue Glazed...",
    slug: "jaipur-persian-quartz-blue-glazed-dinner-plates",
    description: "Crafted without clay from crushed quartz stone, glass, and copper oxide glaze, producing timeless vitreous cobalt beauty.",
    excerpt: "Crafted without clay from crushed quartz stone, glass, and copper oxide glaze, producing timeless vitreous cobalt beauty.",
    story: "Hand-thrown and kiln-glazed by Meenakshi Rathore in Sanganer, reviving royal Persian decorative patterns adapted by Jaipur maharajas.",
    craftType: "Blue Pottery",
    categorySlug: "pottery",
    categoryName: "Pottery",
    regionSlug: "rajasthan",
    regionName: "Rajasthan",
    state: "Rajasthan",
    provenanceTag: "Rajasthan",
    byline: "Meenakshi Rathore",
    dimensions: "10.5\" Diameter per plate (Set of 4)",
    materials: "Powdered quartz stone, natural soda, Fuller's earth, copper oxide glaze",
    careInstructions: "Hand wash with mild soap. Avoid thermal shock.",
    priceDollars: 110.00,
    priceDisplay: "$110",
    pricePaise: 913000,
    originalPricePaise: 1100000,
    stock: 6,
    isMadeToOrder: false,
    leadTimeDays: 3,
    status: "PUBLISHED",
    artisan: ARTISANS.find((a) => a.id === "art-meenakshi") || ARTISANS[3],
    initialFavorited: false,
    images: [
      {
        id: "img-plates-1",
        url: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=1000&q=85",
        altText: "Jaipur Persian Quartz Blue Glazed Dinner Plates stacked on rustic wood",
        isPrimary: true,
      },
    ],
    rating: 4.8,
    reviewCount: 31,
    tags: ["Blue Pottery", "Ceramic Plates", "Quartz", "Rajasthan", "Tableware"],
    createdAt: "2026-09-07T10:00:00Z",
  },

  // 8. Kalamkari Tree of Life (from screenshot)
  {
    id: "prod-kalamkari",
    title: "Kalamkari Tree of Life Hand-Drawn Narrative Scroll",
    shortTitle: "Kalamkari Tree of Life Hand-Drawn...",
    slug: "kalamkari-tree-of-life-hand-drawn-narrative-scroll",
    description: "Srikalahasti freehand temple textile painting executed with bamboo reed pens and natural vegetable pigments.",
    excerpt: "Srikalahasti freehand temple textile painting executed with bamboo reed pens and natural vegetable pigments.",
    story: "Rameshwar Chitrakar sketches the mythical Kalpavriksha tree with iron-acetate ink on myrobalan-treated cotton, washed in the holy Swarnamukhi river.",
    craftType: "Kalamkari Painting",
    categorySlug: "kalamkari-painting",
    categoryName: "Kalamkari Painting",
    regionSlug: "andhra-pradesh",
    regionName: "Andhra Pradesh",
    state: "Andhra Pradesh",
    provenanceTag: "Andhra Pradesh",
    byline: "Rameshwar Chitrakar",
    dimensions: "36\" H × 24\" W",
    materials: "Handspun organic cotton, bamboo reed pen, natural myrobalan and vegetable mordants",
    careInstructions: "Keep out of direct sunlight. Professional textile dry clean only.",
    priceDollars: 320.00,
    priceDisplay: "$320",
    pricePaise: 2656000,
    originalPricePaise: 3100000,
    stock: 2,
    isMadeToOrder: true,
    leadTimeDays: 14,
    status: "PUBLISHED",
    artisan: ARTISANS.find((a) => a.id === "art-rameshwar") || ARTISANS[0],
    initialFavorited: false,
    images: [
      {
        id: "img-kalamkari-1",
        url: "https://images.unsplash.com/photo-1582560475093-ba66accbc424?auto=format&fit=crop&w=1000&q=85",
        altText: "Kalamkari Tree of Life Hand-Drawn Narrative Scroll floral artwork",
        isPrimary: true,
      },
    ],
    rating: 4.9,
    reviewCount: 25,
    tags: ["Kalamkari Painting", "Tree of Life", "Temple Art", "Andhra Pradesh", "Scroll"],
    createdAt: "2026-09-08T10:00:00Z",
  },

  // Supporting items for backwards compatibility:
  {
    id: "prod-lamp",
    title: "Dhokra Lost-Wax Cast Brass Tribal Forest Lamp",
    shortTitle: "Dhokra Lost-Wax Cast Brass Tribal...",
    slug: "dhokra-lost-wax-cast-brass-tribal-forest-lamp",
    description: "Crafted without a single seam using pure beeswax threads coiled around clay armatures, this heirloom sculpture houses soft candlelight.",
    excerpt: "Crafted without a single seam using pure beeswax threads coiled around clay armatures.",
    story: "Subhash Karmakar uses the prehistoric 4,000-year-old lost-wax hollow casting technique of Bankura.",
    craftType: "Dhokra Metal",
    categorySlug: "metalwork",
    categoryName: "Metalwork",
    regionSlug: "west-bengal",
    regionName: "West Bengal",
    state: "West Bengal",
    provenanceTag: "West Bengal",
    byline: "Subhash Karmakar",
    dimensions: "12\" H × 8\" W × 6\" D",
    materials: "Recycled brass, bronze, pure beeswax, alluvial clay core",
    careInstructions: "Dust with a dry brush. Apply brass wax once a year.",
    priceDollars: 210.00,
    priceDisplay: "$210",
    pricePaise: 1735000,
    originalPricePaise: 1950000,
    stock: 3,
    isMadeToOrder: true,
    leadTimeDays: 10,
    status: "PUBLISHED",
    artisan: ARTISANS[2],
    initialFavorited: false,
    images: [
      {
        id: "img-lamp-1",
        url: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1000&q=85",
        altText: "Dhokra Lost-Wax Cast Brass Tribal Forest Lamp artifact",
        isPrimary: true,
      },
    ],
    rating: 4.9,
    reviewCount: 29,
    tags: ["Dhokra", "Bronze", "Lamp", "West Bengal", "Tribal"],
    createdAt: "2026-09-05T09:00:00Z",
  },
  {
    id: "prod-bluepottery-vessel",
    title: "Jaipur Persian Quartz Blue Pottery Vessel",
    shortTitle: "Jaipur Persian Quartz Blue Pottery...",
    slug: "jaipur-persian-quartz-blue-pottery-vessel",
    description: "Unlike traditional ceramics, Jaipur Blue Pottery uses no clay; instead, powdered quartz stone and glass form a durable ceramic.",
    excerpt: "Powdered quartz stone, glass, and natural gums for durable ceramics that endure for centuries.",
    story: "Hand-painted with classical floral arrangements and rich cobalt tones by Leela Devi in Sanganer.",
    craftType: "Blue Pottery",
    categorySlug: "pottery",
    categoryName: "Pottery",
    regionSlug: "rajasthan",
    regionName: "Rajasthan",
    state: "Rajasthan",
    provenanceTag: "Rajasthan",
    byline: "Leela Devi",
    dimensions: "11\" H × 6\" Diameter",
    materials: "Ground quartz, glass, Fuller's earth, copper & cobalt oxides",
    careInstructions: "Wipe clean with a soft microfiber cloth.",
    priceDollars: 94.50,
    priceDisplay: "$94.50",
    pricePaise: 780000,
    originalPricePaise: 920000,
    stock: 7,
    isMadeToOrder: false,
    leadTimeDays: 3,
    status: "PUBLISHED",
    artisan: ARTISANS[3],
    initialFavorited: false,
    images: [
      {
        id: "img-bluepottery-1",
        url: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1000&q=85",
        altText: "Jaipur Persian Quartz Blue Pottery Vessel with classical Dutch floral still life painting",
        isPrimary: true,
      },
    ],
    rating: 4.8,
    reviewCount: 31,
    tags: ["Blue Pottery", "Ceramic", "Rajasthan", "Vase"],
    createdAt: "2026-09-08T14:15:00Z",
  },
  {
    id: "prod-walnut-box",
    title: "Walnut Wood Intricate Lattice Carved Box",
    shortTitle: "Walnut Wood Intricate Lattice...",
    slug: "walnut-wood-intricate-lattice-carved-box",
    description: "Hand-chiseled from a single block of Kashmiri walnut root, featuring deep openwork (Jali) inspired by Mughal palace courtyards.",
    excerpt: "Hand-chiseled from a single block of Kashmiri walnut root, featuring deep openwork.",
    story: "Crafted by Ghulam Rasool from sustainably harvested Kashmiri walnut wood.",
    craftType: "Wood Carving",
    categorySlug: "wood-carving",
    categoryName: "Wood Carving",
    regionSlug: "kashmir",
    regionName: "Kashmir",
    state: "Kashmir",
    provenanceTag: "Kashmir",
    byline: "Ghulam Rasool",
    dimensions: "9\" L × 6\" W × 4\" H",
    materials: "Seasoned walnut root wood, natural wax polish",
    careInstructions: "Keep away from excessive heat or direct moisture.",
    priceDollars: 145.00,
    priceDisplay: "$145",
    pricePaise: 1195000,
    originalPricePaise: 1350000,
    stock: 5,
    isMadeToOrder: false,
    leadTimeDays: 4,
    status: "PUBLISHED",
    artisan: ARTISANS[4],
    initialFavorited: false,
    images: [
      {
        id: "img-walnut-1",
        url: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1000&q=85",
        altText: "Walnut Wood Intricate Lattice Carved Box beside modern minimal plant and clock",
        isPrimary: true,
      },
    ],
    rating: 4.9,
    reviewCount: 22,
    tags: ["Wood Carving", "Walnut", "Kashmir", "Box", "Heirloom"],
    createdAt: "2026-09-10T16:00:00Z",
  },
];

export const REVIEWS: Review[] = [
  {
    id: "rev-1",
    productId: "prod-vase",
    authorName: "Ananya Deshmukh",
    rating: 5,
    title: "Sculptural perfection and authentic craft warmth",
    comment: "The vase looks even more stunning in person than in the photos. The subtle texture of natural terracotta brings tranquility to the room. Devendra Prajapati-ji's touch is evident.",
    verifiedPurchase: true,
    date: "2026-09-12",
    locality: "Bengaluru, Karnataka",
  },
  {
    id: "rev-2",
    productId: "prod-throw",
    authorName: "Rohan Singhal",
    rating: 5,
    title: "True heritage piece with authentic indigo smell",
    comment: "Knowing that this was block printed with 16 stages of river washing makes it a wonderful conversation starter. Ismail Khatri's family is legendary.",
    verifiedPurchase: true,
    date: "2026-09-18",
    locality: "New Delhi",
  },
  {
    id: "rev-3",
    productId: "prod-lamp",
    authorName: "Meera Subramanian",
    rating: 5,
    title: "An absolute treasure of Indian lost-wax casting",
    comment: "To have a genuine Dhokra piece from Bikna is a privilege. The beeswax filigree texture is breathtaking.",
    verifiedPurchase: true,
    date: "2026-09-22",
    locality: "Chennai, Tamil Nadu",
  },
];

export interface GuildPairing {
  id: string;
  title: string;
  categoryTag: string;
  price: string;
  imageUrl: string;
  slug: string;
}

export const GUILD_PAIRINGS: GuildPairing[] = [
  {
    id: "guild-1",
    title: "Hand-Carved Floral High-Relief Sheesham...",
    categoryTag: "WOOD CARVING • RAJASTHAN",
    price: "$700.00",
    imageUrl: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80",
    slug: "walnut-wood-intricate-lattice-carved-box",
  },
  {
    id: "guild-2",
    title: "Sacred Srinathji Gold-Leaf Pichwai...",
    categoryTag: "MINIATURE PAINTING • RAJASTHAN",
    price: "$1500.00",
    imageUrl: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80",
    slug: "jaipur-persian-quartz-blue-pottery-vessel",
  },
  {
    id: "guild-3",
    title: "Dhokra Primitive Tribal Bell-Metal Lost-...",
    categoryTag: "METALWORK • WEST BENGAL",
    price: "$190.00",
    imageUrl: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80",
    slug: "dhokra-lost-wax-cast-brass-tribal-forest-lamp",
  },
  {
    id: "guild-4",
    title: "Zardozi Hand-Embroidered Velvet Wall...",
    categoryTag: "ZARDOZI EMBROIDERY • UTTAR PRADESH",
    price: "$540.00",
    imageUrl: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80",
    slug: "heritage-ajrakh-indigo-hand-block-draped-throw",
  },
];

