import { Artisan, Category, Product, Region, Review } from "@/types";

export const CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "Traditional Pottery & Ceramics",
    slug: "pottery-ceramics",
    description: "Quartz-based blue pottery, terracotta urns, and hand-coiled clayware.",
    imageUrl: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80",
    itemCount: 42,
  },
  {
    id: "cat-2",
    name: "Heritage Handloom & Textiles",
    slug: "handloom-textiles",
    description: "Authentic block-printed silks, Pashmina shawls, and Kalamkari weaves.",
    imageUrl: "https://images.unsplash.com/photo-1606744837616-56c9a5c6a6eb?auto=format&fit=crop&w=800&q=80",
    itemCount: 58,
  },
  {
    id: "cat-3",
    name: "Folk Paintings & Art",
    slug: "folk-paintings",
    description: "Intricate Madhubani, Pattachitra scrolls, and Warli earth murals.",
    imageUrl: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80",
    itemCount: 35,
  },
  {
    id: "cat-4",
    name: "Bell Metal & Dokra",
    slug: "metalcraft",
    description: "Lost-wax cast brass artifacts and engraved copper repoussé.",
    imageUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80",
    itemCount: 29,
  },
  {
    id: "cat-5",
    name: "Woodcarving & Lacquerware",
    slug: "woodcraft",
    description: "Natural vegetable-dyed Channapatna toys and Saharanpur carved teak.",
    imageUrl: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80",
    itemCount: 24,
  },
];

export const REGIONS: Region[] = [
  {
    id: "reg-1",
    name: "Jaipur & Shekhawati",
    slug: "rajasthan",
    state: "Rajasthan",
    description: "Famed for cobalt Persian blue pottery, Dabu mud-resist printing, and camel leather crafts.",
    imageUrl: "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80",
    craftTraditions: ["Jaipur Blue Pottery", "Sanganeri Block Print", "Kundan Meenakari"],
  },
  {
    id: "reg-2",
    name: "Kutch & Saurashtra",
    slug: "gujarat",
    state: "Gujarat",
    description: "A desert landscape alive with Rogan castor-oil painting, Ajrakh geometry, and mirror embroidery.",
    imageUrl: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80",
    craftTraditions: ["Rogan Painting", "Ajrakh Printing", "Rabari Embroidery"],
  },
  {
    id: "reg-3",
    name: "Mithila & Madhubani",
    slug: "bihar",
    state: "Bihar",
    description: "Ancient line art practiced with natural pigments, twigs, and nib-pens across generations of women.",
    imageUrl: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80",
    craftTraditions: ["Madhubani Painting", "Sikki Grass Craft", "Bhojpur Stone Carving"],
  },
  {
    id: "reg-4",
    name: "Channapatna & Mysuru",
    slug: "karnataka",
    state: "Karnataka",
    description: "The 'Gombegala Ooru' (toy town) crafting silky wooden turnery dyed with natural turmeric, indigo, and katha.",
    imageUrl: "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80",
    craftTraditions: ["Channapatna Toys", "Mysore Inlay Woodwork", "Bidriware Metalwork"],
  },
  {
    id: "reg-5",
    name: "Bastar & Kondagaon",
    slug: "chhattisgarh",
    state: "Chhattisgarh",
    description: "Home of primitive 4000-year-old lost-wax hollow brass casting depicting tribal lore and spirit animals.",
    imageUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80",
    craftTraditions: ["Bastar Dokra", "Wrought Iron Craft (Loha Shilp)", "Terracotta Elephants"],
  },
  {
    id: "reg-6",
    name: "Srinagar & Budgam",
    slug: "kashmir",
    state: "Jammu & Kashmir",
    description: "Centuries-old artisanal finesse with hand-spun Pashmina, Sozni needlework, and papier-mâché.",
    imageUrl: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=800&q=80",
    craftTraditions: ["Pashmina Shawls", "Kashmiri Sozni", "Walnut Wood Carving"],
  },
];

export const ARTISANS: Artisan[] = [
  {
    id: "art-1",
    shopName: "Kripal Nilayam Studios",
    slug: "kripal-nilayam",
    artisanName: "Maheshwar Kumbhar",
    bio: "Carrying forward the pioneering revival of Jaipur's quartz-dough blue pottery, crafting heirloom vases without clay.",
    story: "Trained under national masters in Sanganer, Maheshwar mixes quartz, Fuller's earth, and natural plant gum to form vases and platters that never degrade, finished with copper oxide blue and cobalt stains.",
    craftTradition: "Jaipur Blue Pottery",
    state: "Rajasthan",
    locality: "Sanganer, Jaipur",
    isVerified: true,
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=1200&q=80",
    yearsOfExperience: 32,
    featuredQuote: "In blue pottery, no wheel touches clay. We knead the earth from stone, and paint with the calm of indigo.",
    productCount: 14,
  },
  {
    id: "art-2",
    shopName: "Nirona Rogan Heritage",
    slug: "nirona-rogan-heritage",
    artisanName: "Jabbar Khatri",
    bio: "One of the sole remaining family custodial lineages keeping the 400-year-old castor oil Rogan art alive in Kutch.",
    story: "Rogan art requires boiling wild castor oil for two days over earthen kilns until it turns into a thick elastic paste. Jabbar balances a small pea of pigment on his palm, guiding a brass stylus without the stylus ever touching the cloth.",
    craftTradition: "Kutch Rogan Art",
    state: "Gujarat",
    locality: "Nirona, Kutch",
    isVerified: true,
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1606744837616-56c9a5c6a6eb?auto=format&fit=crop&w=1200&q=80",
    yearsOfExperience: 27,
    featuredQuote: "When the thread of paint stretches from my needle into thin air, my breath holds the design.",
    productCount: 9,
  },
  {
    id: "art-3",
    shopName: "Mithilanchal Chitrakala",
    slug: "mithilanchal-chitrakala",
    artisanName: "Sunita Devi Jha",
    bio: "State awardee preserving Kohbar and Bharni styles of Madhubani on handmade handmade lokta paper and raw tussar silk.",
    story: "Sunita learned line geometry from her grandmother on mud-plastered courtyard walls. Today she extracts yellow from turmeric, deep green from broad bean leaves, and ink from lampblack.",
    craftTradition: "Madhubani Line Art",
    state: "Bihar",
    locality: "Ranti, Madhubani",
    isVerified: true,
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1200&q=80",
    yearsOfExperience: 24,
    featuredQuote: "Every blank space in Madhubani must be filled with a flower, a bird, or a drop of rain. Nature leaves no emptiness.",
    productCount: 16,
  },
  {
    id: "art-4",
    shopName: "Bastar Tribal Casting",
    slug: "bastar-tribal-casting",
    artisanName: "Manglu Kashyap",
    bio: "Master Bell Metal smith forging tribal deities, musicians, and oil lamps using ancestral beeswax casting.",
    story: "Using bee wax strings coiled meticulously over clay core models, Manglu pours molten recycled brass into red-hot charcoal pits. Because each wax mould is broken to release the bronze, every single artifact is completely unique.",
    craftTradition: "Bastar Dokra Metal",
    state: "Chhattisgarh",
    locality: "Kondagaon, Bastar",
    isVerified: true,
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1200&q=80",
    yearsOfExperience: 35,
    featuredQuote: "The fire melts the wax away, leaving brass where the bee's work once lived.",
    productCount: 11,
  },
  {
    id: "art-5",
    shopName: "Gombe Craft Collective",
    slug: "gombe-craft-collective",
    artisanName: "Rajanna Gowda",
    bio: "Turning Wrightia tinctoria (Aale mara) wood on traditional foot lathes with non-toxic vegetal lacquer.",
    story: "Rajanna's studio in Channapatna uses sustainably harvested ivory wood that is turned smoothly on power and manual lathes, rubbed with lac infused with turmeric and indigo leaves to achieve an organic glass-like sheen safe for children.",
    craftTradition: "Channapatna Lacquer Wood",
    state: "Karnataka",
    locality: "Channapatna, Ramanagara",
    isVerified: true,
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=300&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1200&q=80",
    yearsOfExperience: 21,
    featuredQuote: "When you hold our wooden toys, you feel smooth warmth. No chemical paint, only trees and natural resin.",
    productCount: 18,
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "prod-1",
    title: "Hand-Painted Cobalt Floral Jaipur Blue Pottery Amphora",
    slug: "jaipur-blue-pottery-floral-amphora",
    description: "An authentic Jaipur blue pottery decorative vase crafted without clay from quartz stone powder, raw glass, and gum, hand-painted with Persian indigo florals.",
    story: "This vase is shaped entirely by hand pressing quartz paste into open moulds. Maheshwar spends over 18 hours painting intricate Persian floral motifs before applying the natural glaze and firing the kiln at 850°C.",
    craftType: "Jaipur Blue Pottery",
    categorySlug: "pottery-ceramics",
    categoryName: "Traditional Pottery & Ceramics",
    regionSlug: "rajasthan",
    regionName: "Jaipur & Shekhawati",
    state: "Rajasthan",
    dimensions: "12\" H × 6.5\" Diameter (approx. 1.2 kg)",
    materials: "Quartz powder, cullet glass, fuller's earth, cobalt oxide, natural glaze",
    careInstructions: "Wipe with a soft damp cloth. Decorative use recommended; avoid boiling liquids.",
    pricePaise: 385000, // ₹3,850
    originalPricePaise: 450000,
    stock: 5,
    isMadeToOrder: false,
    leadTimeDays: 3,
    status: "PUBLISHED",
    artisan: ARTISANS[0],
    images: [
      {
        id: "img-1-1",
        url: "https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=1000&q=85",
        altText: "Jaipur Blue Pottery floral amphora vase in cobalt blue and turquoise",
        isPrimary: true,
      },
      {
        id: "img-1-2",
        url: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=1000&q=85",
        altText: "Hand painted ceramic artisan detail showing brushwork",
      },
    ],
    rating: 4.9,
    reviewCount: 28,
    tags: ["Ceramic", "Blue Pottery", "Home Decor", "Rajasthan", "Vase"],
    createdAt: "2026-08-15T10:00:00Z",
  },
  {
    id: "prod-2",
    title: "Tree of Life Rogan Painted Silk Panel (Framed)",
    slug: "tree-of-life-rogan-painted-silk",
    description: "Exquisite castor-oil paint tapestry on handwoven tussar silk showcasing the symbolic Tree of Life, created with freehand brass stylus without pre-sketching.",
    story: "Master Jabbar Khatri kneads heated castor oil with stone pigments, generating a tactile paint thread. With precise hand-to-eye synchronization, half the tree is drawn and then folded onto itself, achieving miraculous floral symmetry.",
    craftType: "Kutch Rogan Art",
    categorySlug: "folk-paintings",
    categoryName: "Folk Paintings & Art",
    regionSlug: "gujarat",
    regionName: "Kutch & Saurashtra",
    state: "Gujarat",
    dimensions: "24\" × 18\" (Silk area), Museum grade teak frame",
    materials: "Castor oil paste, natural mineral pigments, tussar silk, seasoned teak frame",
    careInstructions: "Keep out of direct sunlight and moisture. Glazed with UV protective glass.",
    pricePaise: 1250000, // ₹12,500
    originalPricePaise: 1400000,
    stock: 2,
    isMadeToOrder: true,
    leadTimeDays: 14,
    status: "PUBLISHED",
    artisan: ARTISANS[1],
    images: [
      {
        id: "img-2-1",
        url: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1000&q=85",
        altText: "Intricate Tree of Life traditional Rogan motif on silk",
        isPrimary: true,
      },
      {
        id: "img-2-2",
        url: "https://images.unsplash.com/photo-1606744837616-56c9a5c6a6eb?auto=format&fit=crop&w=1000&q=85",
        altText: "Detail of castor oil stylus line work",
      },
    ],
    rating: 5.0,
    reviewCount: 14,
    tags: ["Rogan", "Kutch", "Silk", "Heirloom", "Wall Art"],
    createdAt: "2026-08-20T11:30:00Z",
  },
  {
    id: "prod-3",
    title: "Original Kohbar Madhubani Celestial Marriage Scroll",
    slug: "original-kohbar-madhubani-celestial-marriage-scroll",
    description: "An authentic ritual Kohbar painting featuring the Lotus (Purain), sacred fish, sun and moon deities painted with bamboo pens on cow dung treated handmade paper.",
    story: "Sunita Devi renders this auspicious matrimonial blessing using the sacred symbols of fertility and prosperity passed through five centuries of Mithila women. Every dot is drawn by hand using crushed bamboo splints.",
    craftType: "Madhubani Line Art",
    categorySlug: "folk-paintings",
    categoryName: "Folk Paintings & Art",
    regionSlug: "bihar",
    regionName: "Mithila & Madhubani",
    state: "Bihar",
    dimensions: "30\" × 22\" (Unframed archival sheet)",
    materials: "Handmade lokta cotton rag paper, plant & soot pigments, natural gum",
    careInstructions: "Frame under glass with acid-free matting. Protect from humidity.",
    pricePaise: 720000, // ₹7,200
    originalPricePaise: 850000,
    stock: 4,
    isMadeToOrder: false,
    leadTimeDays: 5,
    status: "PUBLISHED",
    artisan: ARTISANS[2],
    images: [
      {
        id: "img-3-1",
        url: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1000&q=85",
        altText: "Traditional Madhubani line painting on handmade paper",
        isPrimary: true,
      },
      {
        id: "img-3-2",
        url: "https://images.unsplash.com/photo-1582561214068-1e434f6998f8?auto=format&fit=crop&w=1000&q=85",
        altText: "Intricate fish and lotus motifs in Mithila art",
      },
    ],
    rating: 4.8,
    reviewCount: 31,
    tags: ["Madhubani", "Folk Art", "Bihar", "Handmade Paper", "Heritage"],
    createdAt: "2026-08-25T14:15:00Z",
  },
  {
    id: "prod-4",
    title: "Bastar Dokra Lost-Wax Bell Metal Elephant with Howdah",
    slug: "bastar-dokra-lost-wax-elephant",
    description: "Ancient hollow-core bronze sculpture of a royal ceremonial elephant with ceremonial bell necklaces and tribal bell-metal riders.",
    story: "Cast in the dense forests of Bastar by Manglu Kashyap. The molten metal takes the place of hand-twisted wax ribbons. No two elephants are identical as the clay mould must be shattered to retrieve the metal sculpture.",
    craftType: "Bastar Dokra Metal",
    categorySlug: "metalcraft",
    categoryName: "Bell Metal & Dokra",
    regionSlug: "chhattisgarh",
    regionName: "Bastar & Kondagaon",
    state: "Chhattisgarh",
    dimensions: "8.5\" H × 9\" L × 4\" W (approx. 2.4 kg)",
    materials: "Recycled brass, copper, natural beeswax, alluvial river clay",
    careInstructions: "Dust regularly with soft dry brush. Brass polish can be lightly applied to high points.",
    pricePaise: 540000, // ₹5,400
    originalPricePaise: 620000,
    stock: 3,
    isMadeToOrder: false,
    leadTimeDays: 4,
    status: "PUBLISHED",
    artisan: ARTISANS[3],
    images: [
      {
        id: "img-4-1",
        url: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1000&q=85",
        altText: "Bastar Dokra antique brass ceremonial elephant sculpture",
        isPrimary: true,
      },
      {
        id: "img-4-2",
        url: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=1000&q=85",
        altText: "Lost wax metal filigree detail",
      },
    ],
    rating: 4.9,
    reviewCount: 19,
    tags: ["Dokra", "Brass", "Sculpture", "Tribal", "Chhattisgarh"],
    createdAt: "2026-09-01T09:00:00Z",
  },
  {
    id: "prod-5",
    title: "Channapatna Hand-Turned Balancing Acrobat & Stacking Tower",
    slug: "channapatna-balancing-acrobat-stacking-tower",
    description: "Child-safe, silky polished wooden stacking and balancing toy turned from soft Wrightia tinctoria wood and polished with organic turmeric and acacia lacquer.",
    story: "Crafted on traditional lathes by Rajanna Gowda. As the wood spins rapidly, a stick of natural lacquer is pressed against it; friction melts the vegetal dye onto the grain, yielding a mirror-smooth finish without chemical varnishes.",
    craftType: "Channapatna Lacquer Wood",
    categorySlug: "woodcraft",
    categoryName: "Woodcarving & Lacquerware",
    regionSlug: "karnataka",
    regionName: "Channapatna & Mysuru",
    state: "Karnataka",
    dimensions: "10\" H × 4.5\" Base (7 interlocking pieces)",
    materials: "Hale wood (Wrightia tinctoria), natural shellac, turmeric yellow, indigo blue, katha brown",
    careInstructions: "Wipe with dry or slightly damp cloth. Do not soak in water.",
    pricePaise: 165000, // ₹1,650
    originalPricePaise: 195000,
    stock: 15,
    isMadeToOrder: false,
    leadTimeDays: 2,
    status: "PUBLISHED",
    artisan: ARTISANS[4],
    images: [
      {
        id: "img-5-1",
        url: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1000&q=85",
        altText: "Channapatna polished wooden stacking toy in warm colors",
        isPrimary: true,
      },
      {
        id: "img-5-2",
        url: "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1000&q=85",
        altText: "Hand crafted wooden pieces with smooth organic lacquer",
      },
    ],
    rating: 4.9,
    reviewCount: 42,
    tags: ["Wooden Toy", "Channapatna", "Natural Lacquer", "Karnataka", "Kids"],
    createdAt: "2026-09-05T12:00:00Z",
  },
  {
    id: "prod-6",
    title: "Hand-Spun Pure Kashmiri Pashmina Stole with Sozni Needlework",
    slug: "kashmiri-pashmina-stole-sozni-needlework",
    description: "Ultra-fine hand-spun Changthangi goat cashmere adorned with delicate Jamawar jaal needle embroidery executed by master craftsmen in Old Srinagar.",
    story: "The raw cashmere is hand-combed from high-altitude nomadic Himalayan goats, spun on traditional yendur wheels, and woven on four-pedal wooden looms. A single stole requires up to three months of patient needlework.",
    craftType: "Pashmina & Sozni",
    categorySlug: "handloom-textiles",
    categoryName: "Heritage Handloom & Textiles",
    regionSlug: "kashmir",
    regionName: "Srinagar & Budgam",
    state: "Jammu & Kashmir",
    dimensions: "80\" L × 28\" W",
    materials: "100% Grade-A Handspun Pashmina Cashmere, Silk embroidery thread",
    careInstructions: "Professional dry clean only. Store wrapped in pure cotton cloth with cedar blocks.",
    pricePaise: 1850000, // ₹18,500
    originalPricePaise: 2100000,
    stock: 3,
    isMadeToOrder: true,
    leadTimeDays: 20,
    status: "PUBLISHED",
    artisan: {
      id: "art-6",
      shopName: "Kashmir Zaffran Looms",
      slug: "kashmir-zaffran-looms",
      artisanName: "Bashir Ahmad Dar",
      bio: "Master weaver carrying four generations of hand-loomed Changthangi Pashmina and micro-needle Sozni traditions.",
      story: "Bashir works with women spinners from Budgam and nomadic Changpa pastoralists in Ladakh to preserve genuine hand-spun pashm that slips effortlessly through a signet ring.",
      craftTradition: "Pashmina & Sozni Weaving",
      state: "Jammu & Kashmir",
      locality: "Downtown Srinagar",
      isVerified: true,
      avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80",
      yearsOfExperience: 38,
      featuredQuote: "A machine can produce fabric in seconds, but only the human pulse can weave warmth into pashm.",
      productCount: 8,
    },
    images: [
      {
        id: "img-6-1",
        url: "https://images.unsplash.com/photo-1606744837616-56c9a5c6a6eb?auto=format&fit=crop&w=1000&q=85",
        altText: "Hand-spun Kashmiri Pashmina stole with fine border embroidery",
        isPrimary: true,
      },
      {
        id: "img-6-2",
        url: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=1000&q=85",
        altText: "Macro view of exquisite Sozni hand embroidery",
      },
    ],
    rating: 5.0,
    reviewCount: 22,
    tags: ["Pashmina", "Cashmere", "Kashmir", "Shawl", "Luxury Handloom"],
    createdAt: "2026-09-10T16:00:00Z",
  },
];

export const REVIEWS: Review[] = [
  {
    id: "rev-1",
    productId: "prod-1",
    authorName: "Ananya Deshmukh",
    rating: 5,
    title: "Mesmerizing craftsmanship and authentic blue finish",
    comment: "The vase looks even more stunning in person than in the photos. The cobalt glaze catches the light gracefully. You can tell this was made by an actual master artisan. Arrived safely packaged with sustainable straw cushions.",
    verifiedPurchase: true,
    date: "2026-09-12",
    locality: "Bengaluru, Karnataka",
  },
  {
    id: "rev-2",
    productId: "prod-1",
    authorName: "Rohan Singhal",
    rating: 5,
    title: "True heritage piece for our living room",
    comment: "Knowing that this was made without a potter's wheel using quartz powder makes it a wonderful conversation starter. Maheshwar-ji's touch is evident.",
    verifiedPurchase: true,
    date: "2026-09-18",
    locality: "New Delhi",
  },
  {
    id: "rev-3",
    productId: "prod-2",
    authorName: "Meera Subramanian",
    rating: 5,
    title: "An absolute treasure of Indian art",
    comment: "To have a genuine Rogan piece from Jabbar Khatri's family is a privilege. The intricate threadwork on silk is breathtaking. Truly fair trade and meaningful.",
    verifiedPurchase: true,
    date: "2026-09-02",
    locality: "Chennai, Tamil Nadu",
  },
  {
    id: "rev-4",
    productId: "prod-5",
    authorName: "Pooja Varma",
    rating: 5,
    title: "Pure joy for our daughter, zero chemical smells",
    comment: "The wood is so smooth it feels like silk. The natural vegetable lacquer colors are vibrant yet earthy. Proud to support our Karnataka toy artisans!",
    verifiedPurchase: true,
    date: "2026-09-22",
    locality: "Pune, Maharashtra",
  },
];
